# Generated by Django 5.2.5 on 2026-02-08 11:57

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0036_booking_pre_ride_reminder_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolvedSosAuditSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.IntegerField(db_index=True)),
                ('trip_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('booking_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resolved_by_username', models.CharField(blank=True, max_length=150, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=timezone.now)),
                ('updated_at', models.DateTimeField(default=timezone.now)),
                ('incident_obj', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_audit_snapshot', to='lets_go.sosincident')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['incident_id'], name='lets_go_res_inciden_7b0e03_idx'),
                    models.Index(fields=['resolved_at'], name='lets_go_res_resolve_34f7c8_idx'),
                    models.Index(fields=['trip_id', 'resolved_at'], name='lets_go_res_trip_id_2a2c16_idx'),
                ],
            },
        ),
    ]
