# Generated by Django 5.2.5 on 2026-02-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0038_merge_0029_history_and_0037_resolved_sos'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bookinghistorysnapshot',
            name='lets_go_boo_trip_fin_74c21c_idx',
        ),
        migrations.RemoveIndex(
            model_name='tripactualpathsummary',
            name='lets_go_tri_trip_gen_d9c1b2_idx',
        ),
        migrations.RenameIndex(
            model_name='bookinghistorysnapshot',
            new_name='lets_go_boo_passeng_2ad89d_idx',
            old_name='lets_go_boo_passeng_b7a0f0_idx',
        ),
        migrations.RenameIndex(
            model_name='bookinghistorysnapshot',
            new_name='lets_go_boo_payment_485958_idx',
            old_name='lets_go_boo_payride_8b820f_idx',
        ),
        migrations.RenameIndex(
            model_name='resolvedsosauditsnapshot',
            new_name='lets_go_res_inciden_602dbc_idx',
            old_name='lets_go_res_inciden_7b0e03_idx',
        ),
        migrations.RenameIndex(
            model_name='resolvedsosauditsnapshot',
            new_name='lets_go_res_resolve_b17979_idx',
            old_name='lets_go_res_resolve_34f7c8_idx',
        ),
        migrations.RenameIndex(
            model_name='resolvedsosauditsnapshot',
            new_name='lets_go_res_trip_id_db4472_idx',
            old_name='lets_go_res_trip_id_2a2c16_idx',
        ),
        migrations.RenameIndex(
            model_name='tripactualpathsummary',
            new_name='lets_go_tri_generat_4218b6_idx',
            old_name='lets_go_tri_generated_70a8c4_idx',
        ),
        migrations.RenameIndex(
            model_name='triphistorysnapshot',
            new_name='lets_go_tri_driver__7154b8_idx',
            old_name='lets_go_tri_driver_f_d3b3f5_idx',
        ),
        migrations.RenameIndex(
            model_name='triphistorysnapshot',
            new_name='lets_go_tri_trip_st_0eba7b_idx',
            old_name='lets_go_tri_status_f_eef5d9_idx',
        ),
        migrations.RenameIndex(
            model_name='triphistorysnapshot',
            new_name='lets_go_tri_trip_da_e6352e_idx',
            old_name='lets_go_tri_date_dep_83b5ab_idx',
        ),
        migrations.AddIndex(
            model_name='bookinghistorysnapshot',
            index=models.Index(fields=['trip_obj', 'finalized_at'], name='lets_go_boo_trip_ob_cdf2c8_idx'),
        ),
        migrations.AddIndex(
            model_name='tripactualpathsummary',
            index=models.Index(fields=['trip_obj', 'generated_at'], name='lets_go_tri_trip_ob_c51a12_idx'),
        ),
    ]
