# Generated by Django 5.2.5 on 2026-02-11 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0039_remove_bookinghistorysnapshot_lets_go_boo_trip_fin_74c21c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteGeometryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_index', models.IntegerField(db_index=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometry_points', to='lets_go.route')),
            ],
            options={
                'ordering': ['route', 'point_index'],
                'indexes': [models.Index(fields=['route', 'point_index'], name='lets_go_rou_route_i_7387f2_idx')],
                'unique_together': {('route', 'point_index')},
            },
        ),
        migrations.CreateModel(
            name='TripActualPathPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_index', models.IntegerField(db_index=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('speed_mps', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='lets_go.tripactualpathsummary')),
            ],
            options={
                'ordering': ['summary', 'point_index'],
                'indexes': [models.Index(fields=['summary', 'point_index'], name='lets_go_tri_summary_93c953_idx')],
                'unique_together': {('summary', 'point_index')},
            },
        ),
    ]
