# Generated by Cascade on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0040_routegeometrypoint_tripactualpathpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='triphistorysnapshot',
            name='actual_path',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
