# Generated by Django 5.0.12 on 2026-02-27 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0044_notifications_support_guests_recipient_key'),
    ]

    operations = []
