# Generated by Django 5.2.5 on 2026-03-13 18:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0045_notificationinbox_offlinenotificationqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2,5}-\\d{1,4}(-[A-Z])?$', 'Enter a valid Pakistani vehicle plate, e.g. "ABC-1234" or "AB-123".')], verbose_name='Registration Number'),
        ),
        migrations.CreateModel(
            name='NotificationInbox',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recipient_key', models.CharField(db_index=True, max_length=128)),
                ('notification_type', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_dismissed', models.BooleanField(db_index=True, default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('push_sent', models.BooleanField(db_index=True, default=False)),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lets_go.guestuser')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lets_go.usersdata')),
            ],
            options={
                'db_table': 'notification_inbox',
                'indexes': [models.Index(fields=['recipient_key', '-created_at'], name='notificatio_recipie_43bfe9_idx'), models.Index(fields=['recipient_key', 'is_read', 'is_dismissed'], name='notificatio_recipie_2fc2d7_idx'), models.Index(fields=['recipient_key', 'push_sent'], name='notificatio_recipie_c323eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='OfflineNotificationQueue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recipient_key', models.CharField(db_index=True, max_length=128)),
                ('is_delivered', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lets_go.guestuser')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lets_go.usersdata')),
            ],
            options={
                'db_table': 'offline_notification_queue',
                'managed': True,
                'indexes': [models.Index(fields=['recipient_key', 'is_delivered', 'created_at'], name='offline_not_recipie_c41326_idx')],
            },
        ),
    ]
