# Generated by Django 5.2.5 on 2026-05-05 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0047_chatbot_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernameregistry',
            name='username',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message="Username must be 3-32 chars, contain at least one letter, and only use letters, numbers, '.' or '_'.", regex='^(?=.*[A-Za-z])[A-Za-z0-9._]{3,32}$')]),
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='accountno',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Account number must be 10-20 digits.', regex='^\\d{10,20}$')]),
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='bankname',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message="Bank name must be 2-50 characters and contain only letters, spaces, '.', '&' or '-'.", regex='^[A-Za-z][A-Za-z .&\\-]{1,48}[A-Za-z.]$')]),
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='driving_license_no',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Driving license number must be 5-20 characters and contain only letters, digits, '-' or '/'.", regex='^[A-Z0-9][A-Z0-9\\-/]{4,19}$')]),
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True, validators=[django.core.validators.RegexValidator(message='IBAN must be a valid Pakistan IBAN (24 chars), e.g. PK36SCBL0000001123456702.', regex='^PK\\d{2}[A-Z]{4}\\d{16}$')]),
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='username',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message="Username must be 3-32 chars, contain at least one letter, and only use letters, numbers, '.' or '_'.", regex='^(?=.*[A-Za-z])[A-Za-z0-9._]{3,32}$')]),
        ),
    ]
