# Generated by Django 5.2.5 on 2026-05-05 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0048_alter_usernameregistry_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='cnic_no',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='CNIC must be in the format 36603-0269853-9', regex='^\\d{5}-\\d{7}-\\d{1}$')]),
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='driving_license_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Driving license number must be 5-20 characters and contain only letters, digits, '-' or '/'.", regex='^[A-Z0-9][A-Z0-9\\-/]{4,19}$')]),
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='phone_no',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in international format, e.g. +923001234567', regex='^\\+\\d{10,15}$')]),
        ),
    ]
