# Generated by Django 5.2.5 on 2026-05-05 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0049_alter_usersdata_cnic_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='bankname',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.RegexValidator(message="Bank name must be 2-120 characters and contain only letters, spaces, '.', '&' or '-'.", regex='^[A-Za-z][A-Za-z .&\\-]{1,118}[A-Za-z.]$')]),
        ),
    ]
