# Generated by Django 6.0.5 on 2026-05-08 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0050_alter_usersdata_bankname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[A-Z0-9\\-]{1,50}$', "Only letters, digits, and '-' are allowed (max 50).")]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[A-Z0-9\\-]{1,50}$', "Only letters, digits, and '-' are allowed (max 50).")]),
        ),
    ]
