# Generated by Django 5.2.5 on 2026-03-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='admintodoitem',
            new_name='administrat_status_bc1a75_idx',
            old_name='admin_todo_status_priority_created',
        ),
        migrations.RenameIndex(
            model_name='admintodoitem',
            new_name='administrat_categor_1f2701_idx',
            old_name='admin_todo_category_status_created',
        ),
        migrations.RenameIndex(
            model_name='admintodoitem',
            new_name='administrat_source__098c3b_idx',
            old_name='admin_todo_source',
        ),
    ]
