# Generated by Django 5.2.5 on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_rename_admin_todo_status_priority_created_administrat_status_bc1a75_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=64, null=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='supportfaq',
            index=models.Index(fields=['is_active', 'priority', 'created_at'], name='administrat_is_activ_7c9b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='supportfaq',
            index=models.Index(fields=['category', 'is_active'], name='administrat_categor_8700f4_idx'),
        ),
    ]
