# Generated by Django 5.2.5 on 2026-04-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_supportfaq'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supportfaq',
            new_name='administrat_is_acti_9c66bb_idx',
            old_name='administrat_is_activ_7c9b0a_idx',
        ),
        migrations.RenameIndex(
            model_name='supportfaq',
            new_name='administrat_categor_a80ec4_idx',
            old_name='administrat_categor_8700f4_idx',
        ),
    ]
