const List<String> pkBankOptions = <String>[
  'Al Baraka Bank (Pakistan) Limited',
  'Allied Bank Limited',
  'Askari Bank Limited',
  'Bank Alfalah Limited',
  'Bank Al Habib Limited',
  'BankIslami Pakistan Limited',
  'Citi Bank N.A. Pakistan',
  'Deutsche Bank A.G. Pakistan',
  'Dubai Islamic Bank Pakistan Limited',
  'Faysal Bank Limited',
  'First Women Bank Limited',
  'Habib Bank Limited (HBL)',
  'Habib Metropolitan Bank Limited',
  'Industrial and Commercial Bank of China (ICBC) Pakistan',
  'JS Bank Limited',
  'MCB Bank Limited',
  'MCB Islamic Bank Limited',
  'Meezan Bank Limited',
  'National Bank of Pakistan (NBP)',
  'Samba Bank Limited',
  'Silkbank Limited',
  'Sindh Bank Limited',
  'Soneri Bank Limited',
  'Standard Chartered Bank (Pakistan) Limited',
  'Summit Bank Limited',
  'The Bank of Khyber',
  'The Bank of Punjab',
  'United Bank Limited (UBL)',

  // Microfinance (Pakistan)
  'Advans Pakistan Microfinance Bank Limited',
  'APNA Microfinance Bank Limited',
  'FINCA Microfinance Bank Limited',
  'First MicroFinanceBank Limited',
  'Khushhali Microfinance Bank Limited',
  'Mobilink Microfinance Bank Limited',
  'National Rural Support Programme (NRSP) Microfinance Bank Limited',
  'Pak Oman Microfinance Bank Limited',
  'Telenor Microfinance Bank Limited',
  'U Microfinance Bank Limited',

  // DFIs (Pakistan)
  'House Building Finance Company Limited (HBFC)',
  'Pakistan Kuwait Investment Company (Private) Limited',
  'Pak-Brunei Investment Company Limited',
  'Pak-China Investment Company Limited',
  'Pak Libya Holding Company (Private) Limited',
  'Pak Oman Investment Company Limited',
  'Saudi Pak Industrial and Agricultural Investment Company Limited',
  'Sindh Modaraba',

  'Other',
];
